### ISSUE TITLE
Survey follow-ups

### ISSUE THREAD

**Issue by Illexpert** [Illexpert/illexpert.com#3]
You should send your interviewees a survey email/link, to start collecting direct feedback. I guess the fun part is figuring out which questions to ask.

**Comment by Illexpert** [comment]
Can you write up some good survey questions? Create a survey monkey? I'll email it to everyone.

**Comment by ezimerman** [comment]
Give me a couple days to think about what questions are most relevant.

Something along the lines of "How would you rate your ***** with Asaf?" Where the **** is the distinct slice of meaning. If you say "How would you rate your interview with Asaf?", you're not getting shit, too broad.

**Comment by ezimerman** [comment]
https://docs.google.com/forms/d/1A2KhNXAFOG37m2wo_4-FZsmQfhMrckYUOim8kaCBYcU/edit?usp=sharing

**Comment by Illexpert** [comment]
I'm thinking surveys come off as a bit stale. this is a reality show for real.
