### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by Illexpert** [Illexpert/illexpert.com#8]
Upload some favicons, for better aesthetic appeal. Reverse: Have you noticed how everyone started getting tattoos in the last 15 years? Not getting a tattoo is like getting a tattoo, it's just different body art. So your missing icons was intentional, from that minimalist pov?

**Comment by Illexpert** [comment]
Do you not see the favicon load for the site? It's a white "e"

**Comment by ezimerman** [comment]
I see the white "e". Please send me your logo in 260x260.

**Comment by Illexpert** [comment]
Here are 2 - Both are 260x260

![ille-260a](https://cloud.githubusercontent.com/assets/1509735/12938795/100c68ac-cf6d-11e5-8fa4-6204915d30d4.png)
![ille-260b](https://cloud.githubusercontent.com/assets/1509735/12938794/100b2d20-cf6d-11e5-9e63-18c3416e692a.png)

**Comment by Illexpert** [comment]
Updated the site, checkout the new favicon, should load the yellow one now

**Comment by ezimerman** [comment]
Do you have a manifest file instructing iOS Android and Windows to use a version of the icon? I can send you the cli for Node, but its easier in html: https://www.dropbox.com/s/xschbcdnvsd8gkk/Logo1.rar?dl=0

**Comment by Illexpert** [comment]
Use zip and you can drag and drop straight into the thread. What do I do with the zip file?

[Logo1.zip](https://github.com/Illexpert/illexpert.com/files/124235/Logo1.zip)

**Comment by ezimerman** [comment]
Drop all of the files into the site root, except for the html file with the respective <head> code.

**Comment by ezimerman** [comment]
Sorry, Github truncated my comment: 

Drop all of the files into the site root, except for the html file with the respective code, which should be inserted into the head tag

**Comment by ezimerman** [comment]
By "all of the files", I mean the files inside the favicons.zip archive.

**Comment by Illexpert** [comment]
Updated site with new favicons -- Though wondering if adding all these icons does anything? Where do I ever see them?

**Comment by ezimerman** [comment]
If you bookmark the site to your iphone or android home screen. It should
also work as a Windows tile, though I havent tested the latter.

**Comment by ezimerman** [comment]
Also, on iPads, and different form-factor devices.
